export global Theme {
    // contains all colors used in the app
    // fs -> fontsize
    // c -> color
    in-out property <length> fs-h1: 28px;
    in-out property <length> fs-h2: 22px;
    in-out property <length> fs-l: 16px; // icons large
    in-out property <length> fs-m: 14px; // normal text
    in-out property <length> fs-s: 12px; // tags

    in-out property <brush> c-txt-norm: #000; // normal text
    in-out property <brush> c-txt-search: #898989; //  searchfield text
    in-out property <brush> c-bg-main: #FFF; // regular background
    in-out property <brush> c-bg-widget: #FFF; // widget background
    in-out property <brush> c-bg-input: #E0E0E0; // search and dropdown background

    // misc colors
    in-out property <brush> c-m-1: #CACACA; // #CACACA Trennlinie

    // suposed to contain accent color and a brighter variant of color
    in-out property <brush> c-ac: #ff0000; // Custom color in darkmode HSL -20 L
    in-out property <brush> c-ac-trans: #ff0000aa; // Custom color 20% transparency
    in-out property <brush> c-ac-light: #ff0000; // Custom color + or - 20 HSL brightnes

    // comon lengths
    in-out property <length> pad: 5px; // padding  for text and button elements
}