import {Theme} from "./theme-struct.slint";
import { IconFA } from "./fa-icon.slint";

enum ButtonTypes {primary, secondary, round, simple}
export component UiButton inherits Rectangle{
    out property <bool> has-hover: toucharea.has-hover;
    in property <ButtonTypes> type: primary;
    in property <string> text: "";
    in property <string> icon: "";

    callback clicked <=> toucharea.clicked;

    border-radius: Theme.fs-m;
    background: Theme.c-ac;
    height: Theme.fs-m + 2 * Theme.pad;
    padding: root.type == ButtonTypes.simple ? 0px : Theme.pad;
    if root.text != "" :Text {
        padding-right: 5px;
        text: root.text;
    }
    if root.icon != "" : IconFA {
        icon-size: Theme.fs-m;
        icon: root.icon;
    }
    toucharea := TouchArea {
        width: root.width;
        height: root.height;
    }
}