// courses_widget.slint
// Widget für die Kursübersicht mit Überschrift, Suchleiste und scrollbarer Liste

import { Button, LineEdit } from "std-widgets.slint";

// Wiederverwendbare Kurskarte
component CoursesWidget {
    preferred-height: 100%;
    preferred-width: 100%;
    HorizontalLayout {
    VerticalLayout {
        alignment: start;
        width: 100%;
        height: 20%;
        Text {
            text: "Deine Kurse";
            horizontal-alignment: left;
            color: black;
            font-size: 30pt;
        }
    VerticalLayout {
        alignment: end;
    }
        Rectangle {
            border-radius: 4px;
            background: #f5f5f5;
            height: 36px;
            width: 15%;
                
                HorizontalLayout {
                    padding: 8px;
                    spacing: 5px;
                    
                    Text {
                        text: "🔍";
                        font-size: 14px;
                        vertical-alignment: center;
                    }
                    
                    LineEdit {
                        placeholder-text: "Kurs suchen";
                        height: 100%;
                        font-size: 14px;
                    }
                    
                }
            }
        }
    VerticalLayout {
        alignment: end;
    }
        Rectangle {
                height: 36px;
                width: 120px;
                border-radius: 4px;
                background: #555555;
                
                Text {
                    text: "Alle anzeigen";
                    color: white;
                    font-size: 20px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
                
                TouchArea {
                    clicked => {
                        // Hier könnte eine Callback-Funktion sein
                    }

    }
        VerticalLayout {
            alignment: center;
            width: 100%;
            height: 80%;
        }
        
    }
}
}