import "./fontawesome-free-6.7.2-desktop/otfs/Font Awesome 6 Free-Regular-400.otf";
export { MyButton, InputField, TagBubble}

component MyButton inherits Rectangle{
    in property <string> name;
    border-radius: 20px;
    background: #f00;
    height: 30px;
    Text {
        text: root.name;
    }
}

component InputField inherits Rectangle{
    //TODO inputfield that can display placeholder and extra icon like search if needed
    property <string> text: "";
    property <string> placeholder: "Edit Me";
    property <string> icon: "\u{f002}";
    property <int> font_size: 26;
    property <int> pad: 5;

    border-radius: 20px;
    background: grey;
    border-width: 0px;
    preferred-height: font_size * 1px + 2px * pad;
    min-width: 80px;

    HorizontalLayout {
        padding: 1px * pad;
        padding-left: 10px;
        padding-right: 10px;
        alignment: space-between;

        //border-width: 0px;
        TextInput {
            if root.text == "" : Text {text: root.placeholder; color: #eee; padding: 0px; x: 0;}
            min-width: 60px; 
            text: root.text;
            accessible-placeholder-text: "Edit Me";
            edited => {root.text = self.text}
        }
        if root.icon != "": Icon := Text{
            font-family: "Font Awesome 6 Free";
            text: root.icon;
        }
    }
}

//component 

//TODO dropdown / select element that takes an array of values and displays them in a predefined manner


//Tag-bubbles small bubbles that take text and color input
component TagBubble inherits Rectangle {
    property <string> text_content: "ON22";
    property <int> font_height;
    property <int> pad: 40;
    property <brush> bg_color: #f00;

    background: root.bg_color;
    border-radius: font_height * 1px + 2px * pad;
    padding: 10px;
    padding-left: 100px;
    Text {
        text: root.text_content;
    }
    
}